// Generated by https://quicktype.io

import { Review } from './Review';

export interface Tour {
    id:           number;
    name:         string;
    description:  string;
    duration:     string;
    maxGroupSize: number;
    difficulty:   string;
    price:        string;
    imageCover:   string;
    createdAt:    string;
    updatedAt:    string;
    locationId:   number;
    guideId:      number;
    tourImgs:     TourImg[];
    user:         User;
    location:     Location;
    reviews:      Review[];
}

export interface Location {
    id:          number;
    name:        string;
    description: string;
    lat:         string;
    long:        string;
    address:     string;
    country:     string;
    createdAt:   string;
    updatedAt:   string;
}

export interface TourImg {
    id:     number;
    url:    string;
    tourId: number | null;
}

export interface User {
    id:               number;
    name:             string;
    email:            string;
    photo:            string;
    password:         string;
    passwordChangeAt: string;
    role:             string;
    status:           string;
    createdAt:        string;
    updatedAt:        string;
}
