// Generated by https://quicktype.io

import { User } from 'src/app/shared/interfaces';

export interface Booking {
    id:           number;
    date:         string;
    peopleNumber: number;
    createdAt:    string;
    updatedAt:    string;
    userId:       number;
    tourId:       number;
    user:         User;
}

