// Generated by https://quicktype.io

import { Location } from '../../locations/interfaces/Location';
import { tourDifficulty } from './tourDifficulty';

export interface TourItem {
    id:           number;
    name:         string;
    description:  string;
    duration:     string;
    maxGroupSize: number;
    difficulty:   tourDifficulty;
    price:        string;
    imageCover:   string;
    createdAt:    string;
    updatedAt:    string;
    locationId:   number;
    guideId:      number;
    tourImgs:     TourImg[];
    location:     Location;
}

export interface TourImg {
    id:     number;
    url:    string;
    tourId: number | null;
}
