// Generated by https://quicktype.io

export interface CreatedBooking {
    id:           number;
    tourId:       number;
    peopleNumber: number;
    date:         string;
    userId:       number;
    updatedAt:    string;
    createdAt:    string;
}
