// Generated by https://quicktype.io

export interface Location {
    id:          number;
    name:        string;
    description: string;
    lat:         number;
    long:        number;
    address:     string;
    country:     string;
    createdAt:   string;
    updatedAt:   string;
}
