// Generated by https://quicktype.io

export interface CountryRes {
    name:         Name;
    capital:      string[];
    altSpellings: string[];
    region:       string;
    subregion:    string;
    latlng:       number[];
    landlocked:   boolean;
    borders:      string[];
    flags:        Flag;
    area:         number;
    startOfWeek:  string;
}

export interface Name {
    common:     string;
    official:   string;
    nativeName: NativeName;
}

export interface NativeName {
    ara: Translation;
}

export interface Translation {
    official: string;
    common:   string;
}

export interface Flag {
    png: string;
    svg: string;
    alt: string;
}
