// Generated by https://quicktype.io

export interface Review {
    id:          number;
    description: string;
    rating:      string;
    createdAt:   string;
    updatedAt:   string;
    userId:      number;
    tourId:      number;
    tour:        TourReview;
}

export interface TourReview {
    id:         number;
    name:       string;
    imageCover: string;
}
