// Generated by https://quicktype.io

export interface ReviewCreated {
    id:          number;
    description: string;
    rating:      string;
    createdAt:   string;
    updatedAt:   string;
    userId:      number;
    tourId:      number;
}
